#server:
#  port: 8084
#
#spring:
#  application:
#    name: nacos-file-upload
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/nacos-user?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    username: root
#    password: Root5683@
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        # enabled: true
#        server-addr: 120.78.189.213:8848/
#
## 端口检查 健康检查
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#qiniuyun:
#  access:
#    key: accesskey
#  secret:
#    key: secretkey
#  bucket:
#    name: my-vlog
#  domainName: http://qiniuyun.lzmvlog.top/
