#spring:
#  application:
#    name: nacos-consumer
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 120.78.189.213:8848
#server:
#  port: 8090
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"